name: Build ThunderTools on Windows

on:
  push:
    branches: ["development/actions-windows-bridge"] # CHANGE TO MASTER
  pull_request:
    branches: ["master"]
 
jobs:
  ThunderNanoServices:
    uses: rdkcentral/ThunderNanoServices/.github/workflows/Build ThunderNanoServices on Windows.yml@master
