name: Build ThunderTools on Linux

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: ["R5_3"]
  pull_request:
    branches: ["R5_3"]
 
jobs:
  Thunder:
    uses: rdkcentral/Thunder/.github/workflows/Linux build template.yml@R5_3
    with:
      thunder_tools_ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

  ThunderInterfaces:
    needs: Thunder
    uses: rdkcentral/ThunderInterfaces/.github/workflows/Linux build template.yml@R5_3

  ThunderLibraries:
    needs: Thunder
    uses: WebPlatformForEmbedded/ThunderLibraries/.github/workflows/Linux build template.yml@R5_3

  ThunderClientLibraries:
    needs: ThunderInterfaces
    uses: rdkcentral/ThunderClientLibraries/.github/workflows/Linux build template.yml@R5_3

  ThunderNanoServices:
    needs: ThunderInterfaces
    uses: rdkcentral/ThunderNanoServices/.github/workflows/Linux build template.yml@R5_3

  ThunderNanoServicesRDK:
    needs: ThunderInterfaces
    uses: WebPlatformForEmbedded/ThunderNanoServicesRDK/.github/workflows/Linux build template.yml@R5_3
